//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class apps
    {
        public int app_id { get; set; }
        public string appName { get; set; }
        public Nullable<double> appPrice { get; set; }
        public Nullable<double> appRate { get; set; }
        public byte[] appImage { get; set; }
    }
}
